language: node_js
node_js:
- '8'
before_install:
- npm install -g grunt-cli istanbul codecov
install:
- npm install
script:
- npm run build
- istanbul cover ./node_modules/mocha/bin/_mocha tests --reporter lcovonly -- -R spec
- codecov
after_success:
- npm pack

# Deployment directives.
# Triggered when tags are pushed.
deploy:

  # Github Releases.
  - provider: releases
    api_key:
      secure: SJcptmzF769gLZjg5Oxpbk5+Pzx43Fk6ol3PAdE/0/9B54doLhtZWCnOL2+2MidKtokjQUYr0+SAzOPrecyzVP0JP0XorhZnUjROQGlwCiReG1orXyGaAQXRiW7VV3gSp5KyPkioS9TmRZ9zANra44WM7na9t+SKdPajXP9jAiEP9D9H7aav3+XvHCpdhRKApQFArtFIbeKP5OgaIEuLPKiQ7tbqF//vfdif8JmViqkpERRvPc4GGCht7CN85I9FJR1qpA1CvBwEHIE8WeszNGiyA7QDoGm2tpjKqftw2cACVYAw9QevjYjHj4dUuzmdSbv4hy7cCp5NajIxS59irvUeoL4lhYY+7GlcBeTF3Wmvc/yNOLXSTe1tRWZmftTJiNAUtBlG6EjFgZGAZUycJoQG+zb85nl8jPjw3NZxRkx8Md7TgHWVpMQAK/pSEpqRr5iHf21V/3sgSaRzcCTPCxc9dvEXJRoIIvC2ny7+ezWOXKyxj1j7hjgpRTyJ0FT14zEzOGlEAzh1opLto0XiIl/XT3T2wLVj//MJ7zZ2OPmma0p0e1Wx1AFCTJTi4eIcEdJjoR5wArinNE0r0WsazfqETvqBzLarxyKv84J5qPp01V1oxpg2cL3O6X8xxMwE+ar7gWuHiwcW6sBJk4SP8LbE7+59v6P4iVxq3NYTPiI=
    file: expressify-js-$TRAVIS_TAG.tgz
    skip_cleanup: true
    on:
      tags: true
      
  # Documentation on Github Pages.
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/dist/
    on:
      tags: true
      
  # NPM tag push.
  - provider: npm
    email: hqm.post@gmail.com
    skip_cleanup: true
    api_key:
      secure: mzDYoN3FDvFpX5gNrcNEe6FjH0VZ9IQoZuaC9KuO16qh0SiHyH1+eBDOyzGZ09HXFufnpRIpQtqJhRAC6fgqKYKWb92ymvvOIPpEK/oNfVQjAXLnL3imUngxtxk68GPL3P9yNSp/LlcYBbMd89Gmpr1uAElC1xnqYnLbmq0PJAUgywKoHzZC+ii2xvRqjWO+FWxQe/adLaWcjyuUiqC6jj5zBCHO8YlbBHb6Y6RCTl6xGTduO8AXYGnLBNyRBgN0du1Ib/0hYCBfJsMT+Z59j/qt5EYQrgFzZBRPQUVNLGpp8wzrZZsqGMYjNkHNVvkrSC61Q6MQjSN9fM7QDinUUyg+UGVZ8QMhRqt18AvqPbdaOL7Jt9eP/8FE2vO0RAFI0wBVdKGqJxgsLEzsGxGFzs/y63Jzy71aue3U31OGNrLh9DZ3oo7X241KqqXIVqQXNdFw1huaOsjlUmTXgHLqmeZTQYE9RhlMH0KT9RntMR4qxJTB0FVc67Csn/zvHLMDMmsTuJDLXuM2iUZawYT40Scigb7wxdTVIWPhIB3gJv0V10QxG0o+Mk7NyiR+nq/qIqwkDpyGVjSYGl0jmDQconKu++Ao6UKZoi+cPm8xLuA30SBbr3GlGXMaUZbJlxlFQgpc7UTGramCHnH1e3IPdK2qOOvnQiKypONZoayt7lk=
    on:
      tags: true
